# Generated by Django 2.0 on 2018-09-12 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('cik', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('symbol', models.CharField(blank=True, max_length=16, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shares', models.IntegerField()),
                ('revenue', models.IntegerField()),
                ('cost_of_revenue', models.IntegerField()),
                ('net_income', models.IntegerField()),
                ('convertible_notes', models.IntegerField()),
                ('equity', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
            ],
            options={
                'ordering': ('date', 'company'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('date', 'company')},
        ),
    ]
